#!/usr/bin/env bash
# Displays 10 times "Holberton School" using a while loop

x=0

while [ $x -le 9 ]
do
  if [ $x -eq 3 ]
  then
    echo "bad luck"
  elif [ $x -eq  7 ]
  then
    echo "good luck"
  else
    echo "Holberton School"
  fi
  ((x++))
done