#!/usr/bin/env bash
# bad number for sime countrys

x=0

while [ $x -le 20 ]
do
  echo "$x"
  case $x in
    "4") echo "bad luck from China"
    ;;
    "9") echo "bad luck from Japan"
    ;;
    "17") echo "bad luck from Italy"
    ;;
  esac
    ((x++))
done